### ISSUE TITLE
music app fc

### ISSUE THREAD

**Issue by satamadeus** [MASVA/MA-XML-7.0-CROATIAN-master#2]
music app fc...mi4c...croatian language...english is ok....

**Comment by MASVA** [comment]
log please
try clear app data

**Comment by satamadeus** [comment]
ma jesam ali ne pomaže...i dalje fc..na engleskom jeziku nema fc...log nemam sada, sutra posaljem

**Comment by satamadeus** [comment]
nije moj mobitel, samo sam ga nadogradio i primjetio navedeno...

**Comment by MASVA** [comment]
koji rom i verzija  je gore ?
pošalji sutra log
jel možeš negdje okačiti aplikaciju da je skinem, na poslu pa sam malo ograničen

**Comment by satamadeus** [comment]
multi 5.12.10 libra....aplikacija je miui defaultna....sutra ću poslati log definitivno...

**Comment by satamadeus** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miui.player/com.miui.player.ui.MusicBrowserActivity}: com.alibaba.fastjson.JSONException: syntax error, position at 0, name download_confirm_button_text
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
at android.app.ActivityThread.access$800(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
at android.os.Handler.dispatchMessage(Handler.java)
at android.os.Looper.loop(Looper.java)
at android.app.ActivityThread.main(ActivityThread.java)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: com.alibaba.fastjson.JSONException: syntax error, position at 0, name download_confirm_button_text
at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:429)
at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1041)
at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1019)
at com.alibaba.fastjson.JSON.parse(JSON.java:89)
at com.alibaba.fastjson.JSON.parse(JSON.java:80)
at com.miui.player.hybrid.toolbox.JSON.parseMap(JSON.java:63)
at com.miui.player.content.LanguageManager.fillTexts(LanguageManager.java:130)
at com.miui.player.content.LanguageManager.prepare(LanguageManager.java:61)
at com.miui.player.content.LanguageManager.<init>(LanguageManager.java:27)
at com.miui.player.content.HybridResources.getLM(HybridResources.java:62)
at com.miui.player.content.FrameConfigData.getString(FrameConfigData.java:90)
at com.miui.player.content.FrameConfigData.getPageTitle(FrameConfigData.java:55)
at com.miui.player.component.MusicNavigatorFragment.initNavigator(MusicNavigatorFragment.java:235)
at com.miui.player.component.MusicNavigatorFragment.onObtainView(MusicNavigatorFragment.java:113)
at com.miui.player.component.MusicHybridFragment.onObtainView(MusicHybridFragment.java:26)
at com.miui.player.component.MusicBaseFragment.onInflateView(MusicBaseFragment.java:153)
at com.miui.player.component.MusicFrameFragment.onInflateView(MusicFrameFragment.java:51)
at com.miui.internal.app.FragmentDelegate.onCreateView(SourceFile:137)
at miui.app.Fragment.onCreateView(SourceFile:62)
at android.app.Fragment.performCreateView(Fragment.java)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
at android.app.BackStackRecord.run(BackStackRecord.java)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
at android.app.Activity.performStart(Activity.java)
... 11 more

**Comment by MASVA** [comment]
koju radnju izvodiš da dođe do te pogreške?
jel uđeš u u aplikaciju, dodaješ pjesme, brišeš itd...

**Comment by satamadeus** [comment]
samo uđem u aplikaciju

**Comment by MASVA** [comment]
verzija ranije je bila u redu?

**Comment by satamadeus** [comment]
kćer mi ima isti model sa prethodnom verzijom softvera i nema problema...ovo je novi mobitel pa sam stavio odmah najnoviji rom i vidio grešku...koja se ne javlja ako stavim jezik na engleski, ali radi se o manjoj curici kojoj je engleski problem..

**Comment by MASVA** [comment]
pokušaj slovački jezik
ako opet zeza onda stavi verziju koja radi dok ne nađemo problem, nema druge
možda je i greška kod compile ROM-a
znači, tražimo rješenje da ne misliš da sam te otkantao
još moram provjeriti dal drugi na redmi note 2 imaju isti problem

lp
Mario

**Comment by satamadeus** [comment]
ma sorry na gnjavaži...kakvo otkantavanje....ja imam mi3w ali on nema ovaj novi rom, tako da to ne pomaže

**Comment by MASVA** [comment]
jel si probao slovački jezik?

**Comment by satamadeus** [comment]
slovački radi

**Comment by MASVA** [comment]
ok tnx

**Comment by MASVA** [comment]
daj mi mail adresu da ti pošaljem nešto

**Comment by satamadeus** [comment]
satamadeus@gmail.com
